// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slgzwapwmsxkryrxrnac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZ3p3YXB3bXN4a3J5cnhybmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MTE4ODEsImV4cCI6MjA2NDA4Nzg4MX0.yX8ps_4ln5xaJ6EfbxcVL3jd1YaGLrc4AOXZih6me5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);